### ISSUE TITLE
When i deploy...

### ISSUE THREAD

**Issue by taewo** [hasankzl/react-flexy-table#13]
Hi @hasankzl 
I'm using this library very well, Thank.

When I working on the localhost, i modify the `node_modules/react-flexy-table/dist/index.modern.js` and 
running `$ npx patch-package react-flexy-table`, It's working well in localhost

But when i deployed by Netlify, Changes not applyed ㅠ

![image](https://user-images.githubusercontent.com/14291977/115483329-8a565680-a28b-11eb-8978-92ee87cb877c.png)

I think  `index.mordern.js`file working on localhost and ` index.mordern.js.map` file working on deploy mode. Is it right?!
So how can i apply the changes in deployment mode ?! 
Thanks 🙏

**Comment by hasankzl** [comment]
Hi taewo,

I'm curious about why you need to change index.mordern.js? Are you trying to add a feauture or fix a bug or something? Maybe we can fix your problem another way.

If netlify build the application for you ,the changes you made doesnt gonna apply on netlify. Because you are making this change in your localhost. Netlify will install all of your dependencies again  and build the application.

But if you are building the application on your local machine using `npm run build` and pasting the build file in netlify. Application should work as wel as in local machine.

If you tell me what you actualy wanna do maybe I can help better.

**Comment by taewo** [comment]
@hasankzl 
This is the part i was curious about!
Thank you so much for detailed answer :>
